# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks

exclude: "setup.py"
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
      - id: check-ast
      - id: check-yaml
      - id: check-json
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-added-large-files
      - id: trailing-whitespace
      - id: end-of-file-fixer
  - repo: https://github.com/pycqa/bandit
    rev: 1.7.0
    hooks:
      - id: bandit
        args: ["-iii", "-ll"]
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.8.4
    hooks:
      - id: flake8
        additional_dependencies: [
            "flake8-bugbear",
            "flake8-comprehensions",
            "flake8-mutable",
            "flake8-print",
            "flake8-simplify",
        ]
  - repo: https://github.com/psf/black
    rev: 20.8b1
    hooks:
      - id: black
  - repo: https://github.com/pycqa/isort
    rev: 5.7.0
    hooks:
      - id: isort
        name: isort (python)
