version: '3.1'

services:
  app:
    build: .
    ports:
    - "80:80"
    environment:
      MONGODB_HOST: "mongo"
      MONGODB_PORT: 27017
      MONGODB_DB: "fiowebviewer"
      MONGODB_USERNAME: "admin"
      MONGODB_PASSWORD: "pass"
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: pass
